Update XLM to GRAM, Update network passphrase, stellar-core to gramr

diff --git a/src/test/selftest-parallel b/src/test/selftest-parallel
--- a/src/test/selftest-parallel
+++ b/src/test/selftest-parallel
@@ -7,7 +7,7 @@
 set -e
 
 # Without this, ACTUAL_NUM_TESTS will be set to 0 if
-# stellar-core throws an exception below.
+# gramr throws an exception below.
 set -o pipefail
 
 export COMMAND="$1"
@@ -42,8 +42,8 @@ perl -e '
          my $num_partitions = $ARGV[0];
          my $test_spec = $ARGV[1];
          my $test_partitions_dir = $ARGV[2];
-         my @all_tests = shuffle `./stellar-core test --ll FATAL --list-test-names-only "$test_spec"`;
-         if ($?) {die "stellar-core failed";}
+         my @all_tests = shuffle `./gramr test --ll FATAL --list-test-names-only "$test_spec"`;
+         if ($?) {die "gramr failed";}
 
          for (my $p = 0; $p < $num_partitions; $p++) {
              open(my $out, ">", "$test_partitions_dir/test-partition-$p.txt");
@@ -60,9 +60,9 @@ NUM_TESTS=0
 for p in $(seq 0 $((NUM_PARTITIONS-1))); do
     NUM_TESTS=$((NUM_TESTS + $(awk 'END{print NR}' $TEST_PARTITIONS_DIR/test-partition-$p.txt)))
 done
-ACTUAL_NUM_TESTS=$(./stellar-core test --ll FATAL --list-test-names-only "$TEST_SPEC" | awk 'END{print NR}')
+ACTUAL_NUM_TESTS=$(./gramr test --ll FATAL --list-test-names-only "$TEST_SPEC" | awk 'END{print NR}')
 if [[ $NUM_TESTS -ne $ACTUAL_NUM_TESTS ]]; then
-    echo "Partitions contain $NUM_TESTS tests, while stellar-core lists $ACTUAL_NUM_TESTS tests"
+    echo "Partitions contain $NUM_TESTS tests, while gramr lists $ACTUAL_NUM_TESTS tests"
     exit 1
 fi
 
